# OFN styleguide for rubocop-rspec
# Because there are so many, we will disable by default, and enable rules as needed.


RSpec:
  Enabled: false

# Enabled rules

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block

RSpec/NotToNot:
  Enabled: true
