name: Linters
on: [pull_request]
permissions:
  contents: write # to fetch code (actions/checkout)  
  pull-requests: write  
  checks: write
  issues: write  
jobs:
  lint:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      # - run: git show --no-patch # the commit being tested (which is often a merge due to actions/checkout@v3)

      #       # - uses: reviewdog/action-setup@v1
      # #   with:
      # #     reviewdog_version: v0.21.0

      # # - run: ./script/reviewdog.sh
      # #   env:
      # #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
      
      - run: bundle exec rubocop -A
      - uses: reviewdog/action-suggester@4747dbc9f9e37adba0943e681cc20db466642158 # v1.21.0
        with:
          tool_name: rubocop
  
